# Generated by Django 4.1 on 2022-09-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=40)),
                ('owner', models.CharField(max_length=40)),
                ('creation_date', models.DateField()),
                ('attribute_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_deadline', models.DateField()),
                ('task_owner', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=40)),
                ('worker_domain', models.CharField(max_length=40)),
                ('worker_email', models.EmailField(max_length=254)),
                ('worker_phone_number', models.PositiveIntegerField()),
            ],
        ),
    ]
