# Generated by Django 4.1 on 2022-09-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creation_date',
        ),
    ]
