# Generated by Django 4.1 on 2022-09-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_creation_date_category_creations_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creations_date',
            new_name='creation_date',
        ),
    ]
