# Generated by Django 4.1 on 2022-09-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_category_creation_date'),
        ('website', '0003_rename_creations_date_category_creation_date'),
    ]

    operations = [
    ]
